Add React v16 features
tonsky/rum pull request #151
Opened 2017-10-29 10:26 UTC by roman01la

Adding new features introduced in React v16

- [x] Error handling via `componentDidMount`
- [x] Return multiple elements from render (supports automatically)
- [x] Portals via `ReactDOM.createPortal`

2017-10-29 12:40 UTC, jetmind commented on src/rum/core.cljs
> +            (vswap! (state this) #(call-all %1 %2 error info) did-update)))))
I believe you've meant `did-catch` here.

Also, you could get rid of anonymous function:

```
(vswap! (state this) call-all did-catch error info)
```

2017-10-29 12:46 UTC, roman01la commented
@jetmind fixed, thanks!

2017-11-08 09:51 UTC, sansolovyov requested changes
@roman01la branch `rum16` at piranha/rum contains changes for server rendering

2017-11-08 09:51 UTC, sansolovyov commented on project.clj
> -            :dependencies [[cljsjs/react-dom-server "15.6.2-0"]
It looks like something was destroyed here?

2017-11-08 09:51 UTC, sansolovyov commented on examples/rum/examples/self_reference.cljc
> +       [:.branch offset (map #(rum/with-key (self-reference % (inc depth)) (str %)) form)]
Also something weird happened here.

2017-11-08 09:51 UTC, sansolovyov commented on examples/rum/examples/multiple_return.cljc
> +  (rum/hydrate (ulist (multiple-return)) mount-el))
And this fails since `rum/hydrate` is only defined in CLJS.

2017-12-20 17:39 UTC, DjebbZ commented
I'd like to chime in since I'm extremely interested in upgrading to React 16. If possible I can try to contribute them (to the extent of my capabilities), and at least review/test them in our app.

Other points of attention that I think need work too:
- The checksum code [isn't necessary anymore](https://reactjs.org/blog/2017/09/26/react-v16.0.html#better-server-side-rendering)
- React doesn't maintain a [whitelist of allowed html attributes](https://reactjs.org/blog/2017/09/26/react-v16.0.html#support-for-custom-dom-attributes) anymore
- What about [streaming HTML](https://reactjs.org/blog/2017/09/26/react-v16.0.html#better-server-side-rendering) ? Open question I think, since it needs support from the webserver used. I don't know what's the best way in Clojure/JVM to stream bits of content : core.async ? some native Java stuff ? I know [pedestal supports various strategies](http://pedestal.io/reference/streaming) for streaming responses. Could be a good inspiration.
- The other features implemented by @roman01la in rum need to be implemented in Sablono too, no ? If not, please explain the relationship between Rum and Sablono as I don't really get it.

PS: I'm commenting only to push things forward, I don't want to be a so-called help vampire. Again, if I can contribute these changes, I'd be happy to as I have some time during this end of 2017 to contribute back to rum.

2017-12-21 10:17 UTC, DjebbZ commented
Answering my own question regarding Sablono : after playing a bit with rum and Sablono in the REPL, I realized that Sablono is used only for the CLJS side of rum to generate proper calls to `js/React.createElement`. For the server-side rum uses its own HTML generator. This one needs to be changed. I'll give it a try.

@roman01la Can you give me access to your `react-16` branch so I can contribute to this PR ?

2017-12-21 10:31 UTC, tonsky commented
> For the server-side rum uses its own HTML generator. This one needs to be changed. I'll give it a try.

What exactly are you going to change and in what direction?

2017-12-21 10:39 UTC, DjebbZ commented
I think mostly the checksum thing (`adler32`) which isn't used anymore in React 16 and the white-list of DOM attributes that isn't necessary anymore.

2017-12-21 11:28 UTC, roman01la commented
@DjebbZ Looks like @piranha did this already in his fork https://github.com/piranha/rum/commit/8e7eaa76153b247431a758f4edfddbb73ef15912

2017-12-21 14:46 UTC, DjebbZ commented
Indeed, looks like he already added some stuff to update to React 16. @piranha, I see that you've already published your fork of scrum to Clojars. Do you plan to do contribute your work back here ?

Also, I think the work to fully support React 16 can't be finished until :
- [Sablono upgrades to React 16](https://github.com/r0man/sablono/issues/178)
- Both Sablono and rum supports an official syntax for Fragment : it's not exactly a sequence of stuff since it doesn't require a `:key` attribute.

Would love your input.

2017-12-21 14:51 UTC, roman01la commented
I don't think that there should be a special syntax for fragments. A fragment is just `js/React.Fragment` component.

2017-12-21 15:16 UTC, DjebbZ commented
`js/React.Fragment` doesn't exist in CLJ side, so we need a hiccup-like way of creating a fragment that will understood by both rum server-side to produce HTML and by Sablono to produce calls to `js/React.Fragment.`

Example : if we assume fragments are not necessary, how do you return several elements at the same level in CLJ ? You can't since only the result of the last expression is returned.

``` clojure
(defc no-fragement []
  [:span 1]
  [:span 2]
  [:span 3])

(no-fragment)
;; => [:span 3] (tested in the REPL)
```

Wrapping all the spans in a vector requires adding a `:key` attribute to each, something fragment doesn't.

2017-12-21 19:34 UTC, piranha commented
@DjebbZ I released it to clojars since we're using that internally. I'm not exactly sure what do you mean if I plan to contribute? I guess I could change this repo, as Nikita gave me permissions, but I never felt like I should, haha. Anyway, I probably should so that he doesn't feel it's a burden, but then I need to test that in our app (I plan to do that next week), and if everything's okay, I guess we'll get some.

Also, about fragments:

```
(defc no-fragement []
  [:span 1]
  [:span 2]
  [:span 3])
```

In this case *obviously* only last expression is returned, since that's semantics of CLJS. I guess the best way to support fragments would be something like that:

```
(defc no-fragement []
  (list
    [:span 1]
    [:span 2]
    [:span 3]))
```

(or with a quote).

2017-12-21 20:39 UTC, rauhs commented
Fragments are different than just returning a collection. You can give fragments a key and you don't have to give the children a key (you do with a coll/array).

IMO, there is nothing to do for Rum with fragments, they're out of scope. This is sablono territory.

2017-12-22 07:29 UTC, rauhs commented
See the reagent ticket I linked, maybe we can decide on a syntax.

2017-12-22 10:14 UTC, DjebbZ commented
@piranha : by contributing it, yes I was meaning merging things back in tonsky's rum repo. I think it's better to have everyone using the same repo, too many forks just fragment the community and it's hard to follow for users.

@piranha @rauhs : yes this is the kind of new syntax support I was talking about that would need to go into Rum server-side rendering. Thanks for the link ! Indeed it needs community agreement.

2017-12-22 14:07 UTC, DjebbZ commented
By the way @piranha, is your fork working well with React 16 ? Noticed any perf boost ?

2017-12-28 17:06 UTC, DjebbZ commented
@r0man has a branch (almost?) working for React 16. [See here](https://github.com/r0man/sablono/pull/181). He's basically waiting a release of rum that supports React 16. But rum depends on Sablono... Chicken and egg problem. So we should try to integrate Sablono in rum and see how it goes, right ? I think I'll try tomorrow.

2018-01-22 11:33 UTC, DjebbZ commented
Bumping. Anyone has advanced the rum/React 16 thing ?

2018-01-27 22:17 UTC, DjebbZ commented
Yesss. Gonna test the new stuff next week for sure. Thank you tonsky.

2018-01-29 15:18 UTC, merged

2018-01-29 15:48 UTC, DjebbZ commented
🎉 🎉  🎉

2018-01-29 16:07 UTC, belucid commented
👍

2018-03-28 07:46 UTC, solidfox commented
Did support for fragments get added to the above or are we still waiting for Sablono?

2018-03-28 07:53 UTC, tonsky commented
no syntax was added

2018-04-03 07:47 UTC, DjebbZ commented
The syntax `:*` was added in Sablono 0.8.3 to support fragment, see the [PR](https://github.com/r0man/sablono/pull/181)

2018-04-03 08:29 UTC, solidfox commented
So if I'm getting this right rum still needs to add server-side support and bump Sablono from 0.8.1 to 0.8.3?

2018-04-03 11:38 UTC, DjebbZ commented
I think so too. I may try it this week.

Le mar. 3 avr. 2018 à 10:29, Daniel Schlaug <notifications@github.com> a
écrit :

> So if I'm getting this right rum still needs to add server-side support
> and bump Sablono from 0.8.1 to 0.8.3?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tonsky/rum/pull/151#issuecomment-378170903>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAEt3mc2o_c6QFb86mUeBZxhlvGyE-H8ks5tkzLxgaJpZM4QKQxm>
> .
>

2018-06-01 15:48 UTC, DjebbZ commented
I started working on fragment support, see PR #167